apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "open-ports-scanner.fullname" . }}
  labels:
    {{- include "open-ports-scanner.labels" . | nindent 4 }}
data:
  NMAP_TARGETS: {{ .Values.config.nmapTargets | quote }}
  NMAP_PORTS: {{ .Values.config.nmapPorts | quote }}
  SEND_REPORT_OPENPORTS_TELEGRAM: {{ .Values.config.sendReportOpenPortsTelegram | quote }}
  SEND_REPORT_NEWOPENPORTS_TELEGRAM: {{ .Values.config.sendReportNewOpenPortsTelegram | quote }}
  
