apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "open-ports-scanner.fullname" . }}
  labels:
    {{- include "open-ports-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.telegramChatId | quote }}
